# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHxEycYJqJooS0mrntIEtvSvbMPQJHnH
"""
import streamlit as st
from PIL import Image
from streamlit_mic_recorder import mic_recorder

st.set_page_config(page_title="AI Plant Assistant", layout="wide")

# UI
st.markdown("""
<style>
.stApp {
    background: linear-gradient(135deg,#1e3c72,#2a5298);
    color:white;
}
</style>
""", unsafe_allow_html=True)

page = st.sidebar.radio("Menu", ["Home","Detection","Voice","Chatbot"])

# HOME
if page == "Home":
    st.title("🌱 AI Smart Plant Assistant")
    st.image("https://images.unsplash.com/photo-1501004318641-b39e6451bec6")

# DETECTION
elif page == "Detection":
    st.title("🌿 Disease Detection")

    file = st.file_uploader("Upload Image")

    if file:
        img = Image.open(file)
        st.image(img)

        st.subheader("Prediction")
        st.write("Leaf Spot Disease")

        st.subheader("Solution")
        st.write("Use fungicide and reduce watering")

# VOICE
elif page == "Voice":
    st.title("🎤 Voice Input")

    audio = mic_recorder()

    if audio:
        st.success("Voice received")
        st.audio(audio["bytes"])

# CHATBOT
elif page == "Chatbot":
    st.title("🤖 Chatbot")

    user = st.text_input("Ask about plants")

    if user:
        st.write("🌿 AI: This could be a fungal infection. Maintain proper care.")
