# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHxEycYJqJooS0mrntIEtvSvbMPQJHnH
"""
import streamlit as st
from PIL import Image
from streamlit_mic_recorder import mic_recorder
import pyttsx3

st.set_page_config(page_title="AI Plant Assistant", layout="wide")

# ---------- BACKGROUND ----------
st.markdown("""
<style>
.stApp {
    background: linear-gradient(135deg, #1e3c72, #2a5298);
    color: white;
}
</style>
""", unsafe_allow_html=True)

# ---------- SIDEBAR ----------
st.sidebar.title("🌿 AI Plant Assistant")
page = st.sidebar.radio("Navigate", ["Home", "Detection", "Chatbot"])

# ---------- HOME ----------
if page == "Home":
    st.title("🌱 AI Smart Plant Assistant")
    st.image("https://images.unsplash.com/photo-1501004318641-b39e6451bec6", use_column_width=True)

    st.markdown("""
    ## 🚀 Features
    - Detect plant diseases  
    - AI suggestions  
    - Voice interaction  
    - Smart chatbot  
    """)

# ---------- DETECTION ----------
elif page == "Detection":
    st.title("🔬 Plant Disease Detection")

    file = st.file_uploader("Upload Image", type=["jpg","png"])

    if file:
        img = Image.open(file)
        st.image(img, use_column_width=True)

        st.success("Analysis Complete")

        disease = "Leaf Spot Disease"
        solution = "Use fungicide and avoid excess watering."

        st.subheader("🧠 Prediction")
        st.write(disease)

        st.subheader("💊 Solution")
        st.write(solution)

        # 🔊 Voice Output
        engine = pyttsx3.init()
        engine.say(solution)
        engine.runAndWait()

    # 🎤 Voice Input
    st.subheader("🎤 Speak")
    audio = mic_recorder()

    if audio:
        st.success("Voice received")

# ---------- CHATBOT ----------
elif page == "Chatbot":
    st.title("🤖 AI Chatbot")

    user = st.text_input("Ask your question")

    if user:
        answer = "This disease is usually caused by fungal infection. Maintain proper care."

        st.write("🌿 AI:", answer)

        # 🔊 Voice response
        engine = pyttsx3.init()
        engine.say(answer)
        engine.runAndWait()
