# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHxEycYJqJooS0mrntIEtvSvbMPQJHnH
"""
import streamlit as st
from PIL import Image
import numpy as np
from streamlit_mic_recorder import mic_recorder
import openai
def set_bg():
    st.markdown(
        """
        <style>
        .stApp {
            background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);
            color: white;
        }

        h1, h2, h3 {
            color: #00ffcc;
        }

        .stButton>button {
            background-color: #00ffcc;
            color: black;
            border-radius: 10px;
        }

        .stTextInput>div>div>input {
            border-radius: 10px;
        }
        </style>
        """,
        unsafe_allow_html=True
    )

set_bg()
# ---------------- SETTINGS ----------------
st.set_page_config(page_title="AI Smart Plant Assistant", page_icon="🌱", layout="wide")

# 👉 Add your OpenAI API key here
openai.api_key = "YOUR_API_KEY_HERE"

# ---------------- SIDEBAR ----------------
st.sidebar.title("🌿 AI Plant Assistant")
page = st.sidebar.radio("Navigate", ["Home", "Demo", "Chatbot", "About"])

# ---------------- HOME ----------------
if page == "Home":
    st.title("🌱 AI Smart Plant Assistant")
    st.subheader("Detect. Diagnose. Protect Crops with AI")

    st.image("https://images.unsplash.com/photo-1501004318641-b39e6451bec6", use_column_width=True)

    st.markdown("""
    ### 🚀 Features:
    - 🧠 AI Disease Detection  
    - 🤖 LLM Chatbot  
    - 🎤 Voice Input  
    - 🌾 Farmer-friendly UI  
    """)

# ---------------- DEMO (ML MODEL) ----------------
elif page == "Demo":
    st.title("🔬 Plant Disease Detection")

    uploaded_file = st.file_uploader("Upload Plant Image", type=["jpg", "png"])

    if uploaded_file:
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Image", use_column_width=True)

        # --- Fake ML Prediction (replace with real model later) ---
        st.success("✅ Analysis Complete")

        st.subheader("🧠 Prediction")
        st.write("Leaf Spot Disease")

        st.subheader("📖 Explanation")
        st.write("Caused by fungal infection due to excess moisture.")

        st.subheader("💊 Treatment")
        st.write("Use fungicide and avoid overwatering.")

    # ---------------- VOICE ----------------
    st.subheader("🎤 Ask using Voice")
    audio = mic_recorder(start_prompt="🎙️ Start", stop_prompt="⏹️ Stop")

    if audio:
        st.success("Voice recorded!")

# ---------------- CHATBOT ----------------
elif page == "Chatbot":
    st.title("🤖 AI Chatbot")

    user_input = st.text_input("Ask anything about plant diseases:")

    if user_input:
        if openai.api_key == "":
            st.warning("Chatbot is in demo mode (no API key).")
            st.write("🌿 AI: This disease may be caused by environmental stress. Please consult an expert.")
        else:
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are an agriculture expert helping farmers."},
                    {"role": "user", "content": user_input}
                ]
            )

            reply = response["choices"][0]["message"]["content"]
            st.write("🌿 AI:", reply)

# ---------------- ABOUT ----------------
elif page == "About":
    st.title("📖 About the Project")

    st.markdown("""
    ### 🌱 AI Smart Plant Assistant

    The **AI Smart Plant Assistant** is an intelligent web application designed to help farmers detect plant diseases and receive instant guidance using Artificial Intelligence and Large Language Models (LLMs).

    ### 🎯 Problem Statement
    Farmers often face difficulty in identifying plant diseases early due to lack of expert support, leading to crop loss and reduced productivity.

    ### 💡 Solution
    This system uses:
    - 🧠 **AI-based image analysis** for disease detection  
    - 🤖 **LLM-powered chatbot** for explanations and guidance  
    - 🎤 **Voice input** for easy interaction  

    ### 🚀 Key Features
    - Upload plant images for disease detection  
    - Get instant diagnosis and treatment suggestions  
    - Ask questions using chatbot  
    - Simple and user-friendly interface  

    ### 🌍 Impact
    - Supports **sustainable agriculture**  
    - Helps farmers make better decisions  
    - Reduces crop damage and financial loss  

    ### 👩‍💻 Developed By
    **Rachel Edwin**  
    BTech CSE (AI & ML)  
    Alliance University  
    """)
